name: mirrorchyan

on:
  workflow_dispatch:

jobs:
  mirrorchyan:
    runs-on: macos-latest
    steps:
      - id: uploading
        uses: MirrorChyan/uploading-action@v1
        with:
          filetype: latest-release
          filename: "MCCA-win-x86_64-*.zip"
          pick_files: '["resource", "interface.json"]'
          exclude_files: '["resource/base/model/ocr/**"]'
          mirrorchyan_rid: MCCA

          owner: MaaXYZ
          repo: MCCA
          github_token: ${{ secrets.GITHUB_TOKEN }}
          upload_token: ${{ secrets.MirrorChyanUploadToken }}