name: mirrorchyan_release_note

on:
  workflow_dispatch:
  release:
    types: [edited]

jobs:
  mirrorchyan:
    runs-on: macos-latest

    steps:
      - id: uploading
        if: ${{ github.repository_owner == 'MaaXYZ' }}
        uses: MirrorChyan/release-note-action@v1
        with:
          mirrorchyan_rid: MCCA

          upload_token: ${{ secrets.MirrorChyanUploadToken }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
